### ISSUE TITLE
Inconsistent behaviour between CLI and Explorer when specifying equality predicate on `WHERE` clause

### ISSUE THREAD

**Issue by prrao87** [kuzudb/explorer#129] opened 2024-03-30 15:13 UTC
This is likely important functionality that's missing (or a bug) in the explorer.

- Kùzu and explorer version: 0.3.2.
- Tested on the [demo dataset](https://github.com/kuzudb/kuzu/tree/master/dataset/demo-db/csv)

The following query works in the CLI and in the Python client (i.e., the core is behaving as expected)

```cypher
MATCH (a:User)-[e:Follows]->(:User {name: "Karissa"})
RETURN a.name AS follower, e.since AS follows_since;
```

Returns a valid result in Python:

```
┌──────────┬───────────────┐
│ follower ┆ follows_since │
│ ---      ┆ ---           │
│ str      ┆ i64           │
╞══════════╪═══════════════╡
│ Adam     ┆ 2020          │
└──────────┴───────────────┘
```

And also in the CLI:

```
kuzu>  MATCH (a:User)-[e:Follows ]->(:User {name: "Karissa"})
..>        RETURN a.name AS follower, e.since AS follows_since;
----------------------------
| follower | follows_since |
----------------------------
| Adam     | 2020          |
----------------------------
(1 tuple)
(2 columns)
Time: 0.67ms (compiling), 2.68ms (executing)
```

However, when the same query is run in Kùzu explorer, it doesn't return anything.

<img width="858" alt="image" src="https://github.com/kuzudb/explorer/assets/35005448/f409da85-662f-44d9-b663-5e3f00755ac8">

I even tested the same query with the WHERE clause, and the results are not consistent between the CLI/client API and Explorer.

```cypher
MATCH (a:User)-[e:Follows]->(b:User)
WHERE b.name = "Karissa"
RETURN a.name AS follower, e.since AS follows_since;
```

<img width="850" alt="image" src="https://github.com/kuzudb/explorer/assets/35005448/a2440eda-b3c2-42ed-a010-1c736ef6c348">

Considering that the explorer uses the Node.js client under the hood, do you think something is off with the query parsing when there are predicates on properties there?

I've only tested via the CLI and the Python client, and they both work as expected, so it's something happening that's specific to the Explorer.

**Comment by mewim** [comment] 2024-04-01 11:44
It seems I cannot reproduce this bug:

Steps I tried:
- Launch Explorer without a database: `docker run -p 8000:8000 --pull=always --rm kuzudb/explorer:latest`
- Load Demo data with Explorer:
<img width="2032" alt="Screenshot 2024-04-01 at 7 40 51 PM" src="https://github.com/kuzudb/explorer/assets/14037726/e1ecbbf4-dc5c-4b70-b4da-debf689f3ff3">
- Run query 1:
<img width="1712" alt="Screenshot 2024-04-01 at 7 41 39 PM" src="https://github.com/kuzudb/explorer/assets/14037726/5cf308f4-20cc-4a64-b019-2fe75d68b288">
- Run query 2:
<img width="1712" alt="Screenshot 2024-04-01 at 7 42 15 PM" src="https://github.com/kuzudb/explorer/assets/14037726/4f960dc9-5b92-43b5-9493-5cf72c2e84a2">

**Comment by mewim** [comment] 2024-04-01 11:47
If you have loaded the dataset on macOS with CLI/Python API and then launch Explorer against the loaded database, this could be due to https://github.com/kuzudb/kuzu/issues/2943 which has been fixed in https://github.com/kuzudb/kuzu/pull/2952 but does not go into any 0.3.x releases due to the storage format change.

**Comment by prrao87** [comment] 2024-04-01 13:23
Ah, that issue might be the reason. Let's keep this open until we release the next version with the storage format change.

**Comment by mewim** [comment] 2024-05-08 16:35
@benjaminwinger I revisited this issue for the latest release of kuzu (v0.4.1) and it seems the issue still exists. I loaded demo-db on macOS (as attached) and the query returns empty result in a Linux Docker container. The issue seems to have not much to do with Explorer, as it is reproducible with CLI as well. Could you please look into it?
[test_db.zip](https://github.com/kuzudb/explorer/files/15252000/test_db.zip)

**Comment by prrao87** [comment] 2024-05-08 17:52
Should we maybe create this as an issue on the Kùzu repo instead?

**Comment by mewim** [comment] 2024-05-08 20:19
Update: this issue seems not reproducible on Linux with x86-64 architecture. When running this query on one of our Linux server, it works fine both locally and in Docker, but when using aarch64 Docker images on Mac with Apple M-series CPU, the issue exists.

**Comment by mewim** [comment] 2024-05-08 20:24
I was also able to reproduce this on an Oracle cloud server with Ampere A1 processor, so this seems to be specific to aarch64 architecture.

**Comment by benjaminwinger** [comment] 2024-05-09 20:56
I don't think this is limited to ARM architectures. I created a branch off v0.4.1 which validates the hash index entries: https://github.com/kuzudb/kuzu/tree/hash-index-init (and also fixes some uninitialized data which made direct comparisons of the hash index files more difficult) and ended up with the following issues when opening the above database on x86_64 linux:
> Fingerprint for key Zhang in slot 28 was 3 but 166 was expected!
Primary slot ID for key Zhang was calculated to be 16 but the key was stored in slot 28
Fingerprint for key Noura in slot 30 was 112 but 114 was expected!
Primary slot ID for key Noura was calculated to be 9 but the key was stored in slot 30
Fingerprint for key Karissa in slot 14 was 25 but 187 was expected!
Primary slot ID for key Karissa was calculated to be 27 but the key was stored in slot 14
Fingerprint for key Guelph in slot 20 was 60 but 3 was expected!
Primary slot ID for key Guelph was calculated to be 6 but the key was stored in slot 20

Notice that `Adam` is not mentioned, so it's pure coincidence that the query is succeeding for that key on linux.
It does look like the hashes still aren't functioning the same on the different platforms.

**Closed** 2024-05-13 20:43 UTC
Labels: bug, invalid
