### ISSUE TITLE
Preview GPT-generated query

### ISSUE THREAD

**Issue by linozen** [kuzudb/explorer#67] opened 2024-01-23 15:21 UTC
Maybe I haven't seen it but there is no obvious way for me to inspect/adapt the GPT-generated cypher query before executing it. This makes the feature much less useful in my opinion.

**Comment by mewim** [comment] 2024-01-23 15:31
<img width="1891" alt="Screenshot 2024-01-23 at 11 28 47 PM" src="https://github.com/kuzudb/explorer/assets/14037726/acf24b70-1496-498b-a778-857a5b31bdf7">
Hi @linozen. After the query is generated, you can click this button to switch this back to the Cypher editor and review the generated queries or make necessary modifications.

**Comment by prrao87** [comment] 2024-07-18 20:02
Closing this as this seems to be working as intended - you just have to click on the "Cypher Code Editor" button to preview the LLM's generated Cypher.

**Closed by prrao87** 2024-07-18 20:02 UTC
